"""Added response votes

Revision ID: 264d730dd5b0
Revises: 141015c35391
Create Date: 2023-11-02 14:55:12.841440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264d730dd5b0'
down_revision = '141015c35391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
